### ISSUE TITLE
ダメージ計算サイトのURLを生成する機能

### ISSUE THREAD

**Issue by Oni-Men** [taichi3012/TheLowTooltipMod#2]
https://taichi3012.github.io/ThelowDamageCalculation/?defaultDamage=334

URLパラメーターに対応したということで、

1. 何かしらのトリガーで手に持ってるアイテムからダメージ計算サイトのURLを生成
2. 生成したURLをチャット欄に貼り付ける
2. ユーザーがクリックすると開く（マイクラの機能）

こういう機能どうでしょう

**Comment by taichi3012** [comment]
武器の情報を簡単に共有できる機能でいいと思います！ただチャットの文字数制限にURLが引っかかることが結構あると思うのでそこ改造していきます。

**Comment by taichi3012** [comment]
こんな感じになりました。
![URL生成](https://user-images.githubusercontent.com/68967462/154137964-89a955a0-7b49-4831-b73a-ae5df5018d1d.png)
